---
- hosts: "{{ openshift_node | default('masters') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  # Define default values for variables that are common between roles
  vars:
    openshift_admin_user: admin
    openshift_admin_pwd: ''
  roles:
    - { role: 'persistence',          tags: 'persistence'}          # When Minishift or oc cluster up is NOT used
    - { role: 'identity_provider',    tags: 'identity_provider'}    # Use HTPasswdPasswordIdentityProvider as Identity Provider -> more secure
    - { role: 'enable_cluster_role',  tags: 'enable_cluster_role'}
    - { role: 'add_extra_users',      tags: 'add_extra_users'}
    - { role: 'delete_extra_users',   tags: 'delete_extra_users'}
    - { role: 'install_oc',           tags: 'install_oc'}           # Install oc client when cluster role is not used
    - { role: 'docker',               tags: 'docker'}               # Enable to access docker on port 2376
    - { role: 'create_projects',      tags: 'create_projects'}
    - { role: 'install_nexus',        tags: 'nexus'}
    - { role: 'install_jenkins',      tags: 'jenkins'}
    - { role: 'install_jaeger',       tags: 'jaeger'}
    - { role: 'install_istio',        tags: 'istio'}
    - { role: 'install_launcher',     tags: 'install-launcher'}
    - { role: 'uninstall_launcher',   tags: 'uninstall-launcher'}
    - { role: 'install_component_crd_operator',  tags: 'component_crd_operator'}
    - { role: 'deploy_snowdrop_site',  tags: 'snowdrop'}
